version: "3.7"
services:
  redis:
    image: redis:5
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./conf/redis.conf:/usr/local/redis/redis.conf"
      - "./data:/data"
    command: ["redis-server", "/usr/local/redis/redis.conf"]
